### ISSUE TITLE
Saved Chat should be retained until deleted

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/chatbot-ui#27]
Was expecting to see saved Chat(s) when logged in again, since did not delete.

Screenshot Example

![saved_chats_should_remain_until_deleted](https://github.com/MicroHealthLLC/chatbot-ui/assets/11938477/e5cdf879-a6aa-4080-bcbb-d7fd93f7149b)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again and let me know.

**Comment by jldroid19** [comment]
@b-solution @LAlexMHllc The data is being saved within the browsers local cache. If I don't clear the cache then my chat's and prompts will persist. If I clear my browser cache all is gone. In order to achieve this we'll need to look into implementing other storage options like a db or we can use a document storage type of approach that will save the chats/prompts in a .json format to a volume we dedicate within the container. We'll need to associate the users login to the chat/prompts with the users unique id.

**Comment by LAlexMHllc** [comment]
Inconsistent behavior. Sometimes the chats/conversions links do not display on the sidebar after user logs back in to the same or different browser.

**Comment by bluenevus** [comment]
this is related to issue 42 and 73
